spring:
  application:
    name: 'forex-convert-service'
  main:
    banner-mode: 'off'
server:
  port: ${PORT:9001}
  servlet:
    context-path: '/forex-convert-service'
eureka:
  instance:
    hostname: 'localhost'
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
app:
  url: 'https://openexchangerates.org/api/convert'
  appId: 'cb11e9b995994725bb5de0fdb0534e86'
